name: Workflow with Custom Action

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get environment variables
      uses: Sumit007521/getEnvVars@feature/update
      with:
        env_name: "development"
        gh_token: ${{ secrets.GH_TOKEN }}
        file_type: "env"  

    - name: Variables Checking
      shell: bash 
      run: |
        echo "PROJECT_NAME: $PROJECT_NAME"
        echo "TARGET_OS: $TARGET_OS"
        echo "BUILD_TYPE: $BUILD_TYPE"
        echo "Maintainer: $MAINTAINER"
        echo "RUN_MODE: $RUN_MODE"
        echo "Variables checked successfully"
        
    - name: Build Application
      shell: bash
      run: |
        echo "Building $RUN_MODE $PROJECT_NAME for $TARGET_OS in $BUILD_TYPE mode"
        echo "Maintainer: $MAINTAINER"
        mkdir build && cd build
        # Simulate build
        echo "Build complete" > ${PROJECT_NAME}_build.txt

    - name: Package Artifacts
      shell: bash
      run: |
        echo "Packaging $RUN_MODE $PROJECT_NAME artifacts"
        zip -r ${PROJECT_NAME}_${TARGET_OS}_${BUILD_TYPE}.zip build

    - name: List Files
      shell: bash 
      run: ls

    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: env_var
        path: |
            env_var.json 
            env_var.txt    

